import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { MapPin, DollarSign } from 'lucide-react';
export const CargoLogistics = ({ data }) => {
    const trailer = data?.trailer;
    const job = data?.job;
    const trailerName = trailer?.name || 'Kein Trailer';
    const trailerAttached = trailer?.attached || false;
    const trailerMass = ((trailer?.mass || 0) / 1000).toFixed(1);
    const sourceCity = job?.sourceCity || '-';
    const destinationCity = job?.destinationCity || '-';
    const income = job?.income || 0;
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "grid grid-cols-2 gap-6", children: [_jsxs("div", { className: "border-l-4 border-blue-500 pl-4", children: [_jsx("div", { className: "text-gray-400 text-xs uppercase tracking-wider mb-2", children: "Fracht" }), _jsx("div", { className: `text-2xl font-bold ${trailerAttached ? 'text-white' : 'text-gray-600'}`, children: trailerAttached ? trailerName : 'Kein Trailer' })] }), trailerAttached && (_jsxs("div", { className: "border-l-4 border-blue-500 pl-4", children: [_jsx("div", { className: "text-gray-400 text-xs uppercase tracking-wider mb-2", children: "Gewicht" }), _jsxs("div", { className: "text-2xl font-bold text-white", children: [trailerMass, _jsx("span", { className: "text-blue-400 text-lg ml-2", children: "t" })] })] }))] }), _jsxs("div", { className: "border-l-4 border-blue-500 pl-4", children: [_jsxs("div", { className: "flex items-center gap-2 text-gray-400 text-xs uppercase tracking-wider mb-3", children: [_jsx(MapPin, { className: "w-4 h-4" }), _jsx("span", { children: "Route" })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("div", { className: "text-center", children: [_jsx("div", { className: "w-6 h-6 rounded-full bg-green-500/30 border border-green-500 flex items-center justify-center mb-2", children: _jsx("div", { className: "w-2 h-2 rounded-full bg-green-500" }) }), _jsx("div", { className: "text-white font-bold text-sm", children: sourceCity })] }), _jsx("div", { className: "flex-1 h-1 bg-gray-700 rounded-full" }), _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "w-6 h-6 rounded-full bg-red-500/30 border border-red-500 flex items-center justify-center mb-2", children: _jsx("div", { className: "w-2 h-2 rounded-full bg-red-500" }) }), _jsx("div", { className: "text-white font-bold text-sm", children: destinationCity })] })] })] }), _jsxs("div", { className: "border-l-4 border-blue-500 pl-4", children: [_jsxs("div", { className: "flex items-center gap-2 text-gray-400 text-xs uppercase tracking-wider mb-2", children: [_jsx(DollarSign, { className: "w-4 h-4" }), _jsx("span", { children: "Verdienst" })] }), _jsxs("div", { className: "text-3xl font-bold text-green-400", children: ["\u20AC", (income || 0).toLocaleString()] })] })] }));
};
